#!/usr/bin/env python3
"""Convert per-model benchmark CSVs in work/csv/ to a LaTeX tables file.

Output: work/tables.tex — one `table` environment per model, booktabs style,
ready for `\\input{tables.tex}` in Overleaf.

Required Overleaf preamble:
    \\usepackage{booktabs}
    \\usepackage{graphicx}   % for \\resizebox
    \\usepackage{multirow}   % for grouped target-pct cell

The output file begins with a `\\providecommand{\\benchscale}{1.0}`. To
enlarge / shrink every table, redefine \\benchscale in the preamble:
    \\renewcommand{\\benchscale}{1.2}   % 120% of \\linewidth
"""
import csv
from itertools import groupby
from pathlib import Path

CSV_DIR = Path("/home/a131/Desktop/Project/work/csv")
OUT_PATH = Path("/home/a131/Desktop/Project/work/tables.tex")
MODEL_ORDER = ["resnet18", "resnet50", "vgg19", "wrn_28_10",
               "mobilenetv2", "googlenet", "squeezenet1_1"]
DISPLAY = {
    "resnet18": "ResNet-18",
    "resnet50": "ResNet-50",
    "vgg19": "VGG-19",
    "wrn_28_10": "WRN-28-10",
    "mobilenetv2": "MobileNetV2",
    "googlenet": "GoogLeNet",
    "squeezenet1_1": "SqueezeNet 1.1",
}

PREAMBLE = r"""% Auto-generated by csv_to_latex.py — do not edit by hand.
% Required packages: booktabs, graphicx, multirow.
%
% Scale knob: change to enlarge/shrink every table (1.0 = fits to \linewidth).
\providecommand{\benchscale}{1.0}
"""


def fmt_num(v, spec, na="--"):
    if v is None or v == "":
        return na
    try:
        return format(float(v), spec)
    except (ValueError, TypeError):
        return na


def fmt_speedup(v):
    s = fmt_num(v, ".2f")
    return s + r"$\times$" if s != "--" else s


def latex_method(name):
    if name == "baseline":
        return "baseline"
    return r"\texttt{" + name.replace("_", r"\_") + "}"


def render_row(target_cell, row):
    cells = [
        target_cell,
        latex_method(row["importance"]),
        fmt_num(row["acc"], ".2f"),
        fmt_num(row["d_acc"], "+.2f"),
        fmt_num(row["lat_ms"], ".2f"),
        fmt_speedup(row["tpu_spd"]),
        fmt_speedup(row["cpu_spd"]),
        fmt_num(row["red_params_pct"], ".1f"),
        fmt_num(row["red_macs_pct"], ".1f"),
        fmt_num(row["size_mb"], ".2f"),
        fmt_num(row["on_chip_mb"], ".2f"),
        fmt_num(row["off_chip_mb"], ".2f"),
    ]
    return " & ".join(cells) + r" \\"


def render_table(model, rows):
    out = []
    out.append(r"\begin{table}[ht]")
    out.append(r"  \centering")
    out.append(rf"  \caption{{{DISPLAY.get(model, model)} pruning benchmark on Edge TPU (INT8).}}")
    out.append(rf"  \label{{tab:bench-{model}}}")
    out.append(r"  \makebox[\linewidth][c]{\resizebox{\benchscale\linewidth}{!}{%")
    out.append(r"  \begin{tabular}{c l rr rrr rr rrr}")
    out.append(r"    \toprule")
    out.append(r"    & & \multicolumn{2}{c}{Accuracy} & \multicolumn{3}{c}{Time} "
               r"& \multicolumn{2}{c}{Reduction (\%)} & \multicolumn{3}{c}{Memory (mb)} \\")
    out.append(r"    \cmidrule(lr){3-4} \cmidrule(lr){5-7} "
               r"\cmidrule(lr){8-9} \cmidrule(lr){10-12}")
    out.append(r"    Target & Importance & Acc & $\Delta$ Acc "
               r"& Lat (ms) & TPU spd & CPU spd "
               r"& Params & MACs "
               r"& Size & On Chip & Off Chip \\")
    out.append(r"    \midrule")

    base = next((r for r in rows if r["importance"] == "baseline"), None)
    if base is not None:
        out.append("    " + render_row("--", base))
        out.append(r"    \midrule")

    pruned = [r for r in rows if r["importance"] != "baseline"]
    groups = [(tgt, list(g)) for tgt, g in groupby(pruned, key=lambda r: r["target_pct"])]
    for gi, (tgt, glist) in enumerate(groups):
        n = len(glist)
        for i, r in enumerate(glist):
            if i == 0:
                left = rf"\multirow{{{n}}}{{*}}{{{tgt}\%}}"
            else:
                left = ""
            out.append("    " + render_row(left, r))
        if gi < len(groups) - 1:
            out.append(r"    \midrule")

    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}}}")
    out.append(r"\end{table}")
    return "\n".join(out)


def render_baseline_speedup(rows):
    out = []
    out.append(r"\begin{table}[ht]")
    out.append(r"  \centering")
    out.append(r"  \caption{Baseline CPU vs TPU latency.}")
    out.append(r"  \label{tab:baseline-speedup}")
    out.append(r"  \begin{tabular}{l rrr}")
    out.append(r"    \toprule")
    out.append(r"    Model & CPU INT8 (ms) & TPU INT8 (ms) & Speedup TPU/CPU \\")
    out.append(r"    \midrule")
    for r in rows:
        cells = [
            DISPLAY.get(r["model"], r["model"]),
            fmt_num(r["cpu_int8_ms"], ".2f"),
            fmt_num(r["tpu_int8_ms"], ".2f"),
            fmt_speedup(r["speedup_tpu_cpu"]),
        ]
        out.append("    " + " & ".join(cells) + r" \\")
    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}")
    out.append(r"\end{table}")
    return "\n".join(out)


def render_quant_speedup(rows):
    out = []
    out.append(r"\begin{table}[ht]")
    out.append(r"  \centering")
    out.append(r"  \caption{FP32 vs INT8 quantization on CPU.}")
    out.append(r"  \label{tab:quant-speedup}")
    out.append(r"  \begin{tabular}{l rrrr}")
    out.append(r"    \toprule")
    out.append(r"    Model & CPU FP32 (ms) & CPU INT8 (ms) & Speedup INT8/FP32 & $\Delta$ Acc \\")
    out.append(r"    \midrule")
    for r in rows:
        cells = [
            DISPLAY.get(r["model"], r["model"]),
            fmt_num(r["cpu_f32_ms"], ".2f"),
            fmt_num(r["cpu_int8_ms"], ".2f"),
            fmt_speedup(r["speedup_int8_f32"]),
            fmt_num(r["d_acc"], "+.2f"),
        ]
        out.append("    " + " & ".join(cells) + r" \\")
    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}")
    out.append(r"\end{table}")
    return "\n".join(out)


def main():
    sections = [PREAMBLE]
    n_tables = 0
    for model in MODEL_ORDER:
        path = CSV_DIR / f"{model}.csv"
        if not path.exists():
            print(f"[skip] no CSV for {model}")
            continue
        with path.open() as f:
            rows = list(csv.DictReader(f))
        sections.append(render_table(model, rows))
        n_tables += 1

    for name, renderer in [("baseline_speedup", render_baseline_speedup),
                            ("quant_speedup", render_quant_speedup)]:
        path = CSV_DIR / f"{name}.csv"
        if not path.exists():
            print(f"[skip] no CSV for {name}")
            continue
        with path.open() as f:
            rows = list(csv.DictReader(f))
        sections.append(renderer(rows))
        n_tables += 1

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n\n".join(sections) + "\n")
    print(f"wrote {OUT_PATH} ({n_tables} tables)")


if __name__ == "__main__":
    main()
